list(
  rd_family_title = list(checkmate  = "Other functions extending the checkmate package:",
                         cli        = "Other functions extending the cli package:",
                         commonmark = "Other CommonMark parsing functions:",
                         desc       = "Other package `DESCRIPTION` functions:",
                         df         = "Other data frame / tibble functions:",
                         dots       = "Other dots functions:",
                         git        = "Other Git functions:",
                         htmlwidget = "Other HTML widget functions:",
                         http       = "Other HTTP functions:",
                         list       = "Other list functions:",
                         md         = "Other (Pandoc) Markdown functions:",
                         path       = "Other path functions:",
                         rmd_format = "Other R Markdown output formats:",
                         rmd_knitr  = "Other R Markdown and knitr functions:",
                         roxy       = "Other package documentation functions:",
                         rpkgs      = "Other R package functions:",
                         stat       = "Other statistical computing / numeric functions:",
                         string     = "Other string functions:",
                         sys        = "Other system interaction functions:",
                         toml       = "Other TOML functions:")
)
