# DO NOT EDIT THIS FILE BY HAND! Instead edit the R Markdown source file `Rmd/supporter.Rmd`.
# See `README.md#development` for more information on the literature programming approach used applying the R Markdown format.

is_installed <- function(pkg)
{
  nzchar(system.file(package = pkg))
}

script_path <- function()
{
  cmd_args <- commandArgs(trailingOnly = FALSE)
  needle <- "--file="
  match <- grep(x = cmd_args,
                pattern = needle)
  
  if ( length(match) > 0 )
  {
    # Rscript
    return(normalizePath(sub(needle, "", cmd_args[match])))
    
  } else
  {
    if ( !is.null(sys.frames()[[1]]$ofile) )
    {
      # `source()`d via R console
      return(normalizePath(sys.frames()[[1]]$ofile))
      
      # RStudio Run Selection, cf. http://stackoverflow.com/a/35842176/2292993  
    } else if ( is_installed("rstudioapi") )
    {
      return(normalizePath(rstudioapi::getActiveDocumentContext()$path))

    } else rlang::abort("Couldn't determine script path!'")
  }
}

cat_lines <- function(x)
{
  cat(as.character(unlist(x)),
      sep = "\n")
}
